[package]
name = "mytodo"
version = "0.1.0"
authors = ["winsan"]
edition = "2018"

[workspace]
members = ["backend", "frontend"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { version="^1.0.85", features = ['derive'] }

